CREATE TABLE Algorithms (
    AlgorithmID INT NOT NULL AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Type VARCHAR(255) NOT NULL,
    Complexity VARCHAR(255) NOT NULL
);

CREATE TABLE ApplicationsAreas (
    AreaID INT NOT NULL AUTO_INCREMENT,
    AreaName VARCHAR(255) NOT NULL
);
